/**
 * Calibrated Keno pay tables — 80-number grid, 20 numbers drawn per round, pick 1–10.
 *
 * Generated by scripts/calibrate-keno.mjs using exact hypergeometric probabilities.
 * Each table is scaled so realized RTP <= 99% (house-favorable). Multipliers are
 * floored so no table ever exceeds the target return. Do not hand-edit — re-run
 * the generator and paste the JSON if the model changes.
 */

export type KenoRisk = 'low' | 'medium' | 'high'

export const KENO_GRID = 80
export const KENO_DRAWN = 20
export const KENO_MAX_PICKS = 10

// hitCount -> multiplier. Missing hitCounts pay 0.
export const KENO_MULTIPLIERS: Record<KenoRisk, Record<number, Record<number, number>>> = {
  low: {
    1: { 1: 3.95 },
    2: { 1: 2, 2: 3.8 },
    3: { 2: 5.99, 3: 11 },
    4: { 2: 3.23, 3: 6.14, 4: 11 },
    5: { 3: 9.06, 4: 17, 5: 32 },
    6: { 3: 5.04, 4: 9.59, 5: 18, 6: 34 },
    7: { 4: 13, 5: 26, 6: 50, 7: 95 },
    8: { 4: 7.85, 5: 14, 6: 28, 7: 53, 8: 102 },
    9: { 5: 21, 6: 41, 7: 77, 8: 148, 9: 281 },
    10: { 5: 12, 6: 23, 7: 44, 8: 84, 9: 161, 10: 306 },
  },
  medium: {
    1: { 1: 3.95 },
    2: { 2: 16 },
    3: { 2: 5.57, 3: 15 },
    4: { 3: 19, 4: 53 },
    5: { 3: 8.05, 4: 22, 5: 63 },
    6: { 4: 25, 5: 72, 6: 203 },
    7: { 5: 90, 6: 254, 7: 713 },
    8: { 5: 37, 6: 105, 7: 295, 8: 826 },
    9: { 6: 129, 7: 362, 8: 1014, 9: 2841 },
    10: { 6: 57, 7: 161, 8: 451, 9: 1263, 10: 3539 },
  },
  high: {
    1: { 1: 3.95 },
    2: { 2: 16 },
    3: { 3: 71 },
    4: { 3: 17, 4: 74 },
    5: { 4: 66, 5: 280 },
    6: { 5: 272, 6: 1143 },
    7: { 6: 1186, 7: 4982 },
    8: { 6: 317, 7: 1333, 8: 5602 },
    9: { 7: 1335, 8: 5608, 9: 23556 },
    10: { 8: 6069, 9: 25492, 10: 107069 },
  },
}

/** Multiplier for a given risk/pick-count/hit-count (0 if not a paying tier). */
export function kenoMultiplier(risk: KenoRisk, picks: number, hits: number): number {
  return KENO_MULTIPLIERS[risk]?.[picks]?.[hits] ?? 0
}
