/**
 * Calibrated Keno pay tables — 40-number grid, 10 numbers drawn per round, pick 1–10.
 *
 * Generated by scripts/calibrate-keno.mjs using exact hypergeometric probabilities.
 * Each table is scaled so realized RTP <= 99% (house-favorable). Multipliers are
 * floored so no table ever exceeds the target return. Do not hand-edit — re-run
 * the generator and paste the JSON if the model changes.
 */

export type KenoRisk = 'low' | 'medium' | 'high'

export const KENO_GRID = 40
export const KENO_DRAWN = 10
export const KENO_MAX_PICKS = 10

// hitCount -> multiplier. Missing hitCounts pay 0.
export const KENO_MULTIPLIERS: Record<KenoRisk, Record<number, Record<number, number>>> = {
  low: {
    1: { 1: 3.95 },
    2: { 1: 2, 2: 3.8 },
    3: { 2: 6.19, 3: 11 },
    4: { 2: 3.32, 3: 6.32, 4: 12 },
    5: { 3: 10, 4: 19, 5: 36 },
    6: { 3: 5.51, 4: 10, 5: 19, 6: 37 },
    7: { 4: 17, 5: 32, 6: 61, 7: 116 },
    8: { 4: 9.45, 5: 17, 6: 34, 7: 64, 8: 123 },
    9: { 5: 31, 6: 58, 7: 112, 8: 212, 9: 404 },
    10: { 5: 17, 6: 32, 7: 62, 8: 118, 9: 224, 10: 426 },
  },
  medium: {
    1: { 1: 3.95 },
    2: { 2: 17 },
    3: { 2: 5.8, 3: 16 },
    4: { 3: 21, 4: 60 },
    5: { 3: 9.07, 4: 25, 5: 71 },
    6: { 4: 33, 5: 93, 6: 260 },
    7: { 5: 143, 6: 403, 7: 1128 },
    8: { 5: 58, 6: 162, 7: 456, 8: 1277 },
    9: { 6: 268, 7: 750, 8: 2102, 9: 5886 },
    10: { 6: 115, 7: 322, 8: 903, 9: 2530, 10: 7085 },
  },
  high: {
    1: { 1: 3.95 },
    2: { 2: 17 },
    3: { 3: 81 },
    4: { 3: 20, 4: 84 },
    5: { 4: 88, 5: 371 },
    6: { 5: 450, 6: 1890 },
    7: { 6: 2712, 7: 11393 },
    8: { 6: 709, 7: 2981, 8: 12520 },
    9: { 7: 4663, 8: 19587, 9: 82265 },
    10: { 8: 40243, 9: 169022, 10: 709895 },
  },
}

/** Multiplier for a given risk/pick-count/hit-count (0 if not a paying tier). */
export function kenoMultiplier(risk: KenoRisk, picks: number, hits: number): number {
  return KENO_MULTIPLIERS[risk]?.[picks]?.[hits] ?? 0
}
