/**
 * Calibrated Plinko bucket multipliers.
 *
 * A fair ball falls through `rows` pins and lands in bucket j (0..rows) with
 * binomial probability C(rows, j) / 2^rows. Buckets are symmetric — center is a
 * loss (<1x), edges pay big. Generated by scripts/calibrate-plinko.mjs and
 * floored so realized RTP <= 99% (house-favorable). Do not hand-edit.
 */

export type PlinkoRisk = 'low' | 'medium' | 'high'
export type PlinkoRows = 8 | 12 | 16

export const PLINKO_ROWS_OPTIONS: PlinkoRows[] = [8, 12, 16]
export const PLINKO_RISKS: PlinkoRisk[] = ['low', 'medium', 'high']

export const PLINKO_MULTIPLIERS: Record<PlinkoRows, Record<PlinkoRisk, number[]>> = {
  8: {
    low: [2.6, 1.83, 1.29, 0.9, 0.64, 0.9, 1.29, 1.83, 2.6],
    medium: [5.98, 2.99, 1.49, 0.74, 0.37, 0.74, 1.49, 2.99, 5.98],
    high: [16, 4.89, 1.48, 0.44, 0.13, 0.44, 1.48, 4.89, 16],
  },
  12: {
    low: [3.42, 2.59, 1.96, 1.49, 1.12, 0.85, 0.64, 0.85, 1.12, 1.49, 1.96, 2.59, 3.42],
    medium: [12, 6.68, 3.71, 2.06, 1.14, 0.63, 0.35, 0.63, 1.14, 2.06, 3.71, 6.68, 12],
    high: [57, 20, 7.04, 2.47, 0.86, 0.3, 0.1, 0.3, 0.86, 2.47, 7.04, 20, 57],
  },
  16: {
    low: [4.39, 3.45, 2.72, 2.14, 1.68, 1.32, 1.04, 0.82, 0.64, 0.82, 1.04, 1.32, 1.68, 2.14, 2.72, 3.45, 4.39],
    medium: [19, 11, 7.26, 4.4, 2.66, 1.61, 0.98, 0.59, 0.36, 0.59, 0.98, 1.61, 2.66, 4.4, 7.26, 11, 19],
    high: [183, 70, 27, 10, 4.01, 1.54, 0.59, 0.22, 0.08, 0.22, 0.59, 1.54, 4.01, 10, 27, 70, 183],
  },
}

export function plinkoBuckets(rows: PlinkoRows, risk: PlinkoRisk): number[] {
  return PLINKO_MULTIPLIERS[rows][risk]
}

/** Color intent for a bucket by multiplier, so the board grades center->edge. */
export function plinkoBucketTier(mult: number): 'cold' | 'low' | 'mid' | 'hot' | 'max' {
  if (mult >= 50) return 'max'
  if (mult >= 5) return 'hot'
  if (mult >= 1.5) return 'mid'
  if (mult >= 1) return 'low'
  return 'cold'
}
